"use client";

import { useEffect, useMemo, useState } from "react";
import QRCode from "react-qr-code";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { ProgressBar } from "@/components/ui/ProgressBar";
import { encryptFileClientSide, EncryptedPayload, generateCode } from "@/lib/crypto-client";

const MAX_FILE_SIZE_BYTES = 30 * 1024 * 1024;
const TTL_SECONDS = 15 * 60;

type UploadPhase = "idle" | "encrypting" | "uploading" | "done" | "error";

export function SendPanel() {
  const [file, setFile] = useState<File | null>(null);
  const [code, setCode] = useState<string>("");
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [phase, setPhase] = useState<UploadPhase>("idle");
  const [uploadProgress, setUploadProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [expiresAt, setExpiresAt] = useState<string | null>(null);
  const [startedAt, setStartedAt] = useState<number | null>(null);
  const router = useRouter();

  useEffect(() => {
    if (!code) {
      const generated = generateCode(6);
      setCode(generated);
      setAutoGenerated(true);
      if (navigator.clipboard?.writeText) {
        navigator.clipboard.writeText(generated).catch(() => undefined);
      }
    }
  }, [code]);

  const expiryCountdown = useMemo(() => {
    if (!expiresAt) return null;
    const expiry = new Date(expiresAt).getTime();
    const now = Date.now();
    const diffMs = expiry - now;
    if (diffMs <= 0) return "expired";
    const totalSeconds = Math.floor(diffMs / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, "0")}`;
  }, [expiresAt, phase]);

  const transferUrl =
    typeof window !== "undefined" && code
      ? `${window.location.origin}/receive?code=${code}`
      : "";

  const estimatedRemaining = useMemo(() => {
    if (!startedAt || uploadProgress <= 0 || uploadProgress >= 100) return null;
    const elapsed = (Date.now() - startedAt) / 1000;
    const rate = uploadProgress / elapsed;
    if (rate <= 0) return null;
    const remainingProgress = 100 - uploadProgress;
    const remainingSeconds = Math.round(remainingProgress / rate);
    const minutes = Math.floor(remainingSeconds / 60);
    const seconds = remainingSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, "0")}`;
  }, [uploadProgress, startedAt]);

  async function handleUpload() {
    if (!file) {
      setError("Choose a file up to 30 MB.");
      return;
    }
    if (file.size > MAX_FILE_SIZE_BYTES) {
      setError("File exceeds 30 MB limit.");
      return;
    }
    if (!code || code.length < 4) {
      setError("Code must be at least 4 digits.");
      return;
    }

    setError(null);
    setPhase("encrypting");
    setUploadProgress(0);

    try {
      const payload: EncryptedPayload = await encryptFileClientSide(file, code, TTL_SECONDS);
      setExpiresAt(payload.expiresAt);
      setPhase("uploading");
      setStartedAt(Date.now());

      const body = JSON.stringify(payload);
      const total = body.length;

      await new Promise<void>((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("POST", "/api/transfers", true);
        xhr.setRequestHeader("Content-Type", "application/json");

        xhr.upload.onprogress = (event) => {
          if (event.lengthComputable) {
            const percent = (event.loaded / event.total) * 100;
            setUploadProgress(percent);
          } else {
            const loaded = xhr.upload ? (event as any).loaded ?? 0 : 0;
            const percent = (loaded / total) * 100;
            setUploadProgress(percent);
          }
        };

        xhr.onload = () => {
          if (xhr.status >= 200 && xhr.status < 300) {
            setUploadProgress(100);
            resolve();
          } else {
            reject(new Error("Upload failed"));
          }
        };

        xhr.onerror = () => reject(new Error("Upload failed"));
        xhr.send(body);
      });

      setPhase("done");
      if (navigator.clipboard?.writeText) {
        navigator.clipboard.writeText(code).catch(() => undefined);
      }
    } catch (err: any) {
      console.error(err);
      setPhase("error");
      setError("Something went wrong while encrypting or uploading.");
    }
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    if (f.size > MAX_FILE_SIZE_BYTES) {
      setError("File exceeds 30 MB limit.");
      setFile(null);
      return;
    }
    setError(null);
    setFile(f);
  };

  const handleCopy = () => {
    if (!code) return;
    navigator.clipboard?.writeText(code).catch(() => undefined);
  };

  return (
    <section className="flex flex-1 flex-col rounded-3xl border border-slate-800/70 bg-transparent p-5 sm:p-7">
      <div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-xl font-semibold tracking-tight sm:text-2xl">
            Send a file
          </h1>
          <p className="mt-1 text-sm text-neutral-500">
            Drop a file, share the code, pick it up on another device.
          </p>
        </div>
        {expiresAt && (
          <div className="rounded-full border border-neutral-800 bg-neutral-900/80 px-3 py-1 text-xs text-neutral-300">
            Expires in{" "}
            <span className="tabular-nums text-neutral-100">
              {expiryCountdown ?? "…"}
            </span>
          </div>
        )}
      </div>

      <div className="grid gap-6 md:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
        <div className="space-y-4">
          <div className="rounded-2xl border border-dashed border-neutral-800/80 bg-neutral-950/80 p-4">
            <label className="flex cursor-pointer flex-col justify-between gap-3 sm:flex-row sm:items-center">
              <div>
                <p className="text-sm font-medium text-neutral-50">
                  File (max 30 MB)
                </p>
              </div>
              <span className="rounded-full bg-neutral-100 px-3 py-1 text-xs font-medium text-black">
                Browse…
              </span>
              <input
                type="file"
                className="hidden"
                onChange={handleFileChange}
              />
            </label>
            {file && (
              <div className="mt-3 rounded-xl bg-neutral-900/90 px-3 py-2 text-xs text-neutral-200">
                <div className="flex items-center justify-between gap-2">
                  <span className="line-clamp-1">{file.name}</span>
                  <span className="tabular-nums text-neutral-400">
                    {(file.size / (1024 * 1024)).toFixed(2)} MB
                  </span>
                </div>
              </div>
            )}
          </div>

          <div className="space-y-2">
            <label className="block text-xs font-medium text-neutral-300">
              Code
            </label>
            <div className="flex items-center gap-2">
              <Input
                value={code}
                onChange={(e) => {
                  const next = e.target.value.replace(/\\D/g, "").slice(0, 6);
                  setAutoGenerated(false);
                  setCode(next);
                }}
                inputMode="numeric"
                pattern="\\d*"
                maxLength={6}
                className="w-32 tabular-nums text-center text-lg tracking-[0.2em]"
              />
              <Button type="button" variant="ghost" onClick={handleCopy}>
                Copy
              </Button>
            </div>
          </div>

          <div className="space-y-3">
            <Button
              type="button"
              onClick={handleUpload}
              disabled={phase === "encrypting" || phase === "uploading"}
              className="w-full justify-center"
            >
              {phase === "idle" && "Encrypt & upload"}
              {phase === "encrypting" && "Encrypting…"}
              {phase === "uploading" && "Uploading…"}
              {phase === "done" && "File ready to receive"}
              {phase === "error" && "Retry upload"}
            </Button>
            {(phase === "encrypting" || phase === "uploading" || phase === "done") && (
              <div className="space-y-1">
                <ProgressBar value={phase === "encrypting" ? 10 : uploadProgress} />
                <div className="flex justify-between text-[11px] text-neutral-500">
                  <span>
                    {phase === "encrypting"
                      ? "Encrypting locally…"
                      : phase === "uploading"
                      ? `Uploading… ${uploadProgress.toFixed(0)}%`
                      : "Encrypted upload complete"}
                  </span>
                  {estimatedRemaining && phase === "uploading" && (
                    <span>~{estimatedRemaining} remaining</span>
                  )}
                </div>
              </div>
            )}
            {error && <p className="text-xs text-red-400">{error}</p>}
            {!error && (
              <p className="text-[11px] text-neutral-500">
                Up to 30 MB per transfer. Images, PDFs, text files, and ZIP archives work
                best.
              </p>
            )}
          </div>
        </div>

        <div className="flex flex-col gap-4 rounded-2xl border border-neutral-800 bg-neutral-950/60 p-4">
          <p className="text-xs font-medium uppercase tracking-[0.18em] text-neutral-500">
            Receive on another device
          </p>
          <div className="flex flex-1 flex-col items-center justify-center gap-3">
            {code && transferUrl ? (
              <>
                <div className="rounded-3xl bg-white p-4 shadow-[0_12px_40px_rgba(0,0,0,0.45)]">
                  <QRCode
                    value={transferUrl}
                    size={140}
                    style={{ height: "auto", width: "140px" }}
                  />
                </div>
                <div className="text-center text-xs text-neutral-400">
                  Scan on your phone to open{" "}
                  <span className="font-medium text-neutral-100">
                    /receive?code={code}
                  </span>
                  .
                </div>
              </>
            ) : (
              <div className="h-32 w-full rounded-2xl border border-dashed border-neutral-800 bg-neutral-950/60" />
            )}
          </div>
          <div className="mt-2">
            <Button
              type="button"
              variant="ghost"
              className="w-full justify-center text-xs"
              onClick={() => router.push(`/receive?code=${code}`)}
            >
              Open receive on this device
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}

